# Generated by Django 4.2.1 on 2023-06-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_alter_post_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post",
            unique_together=set(),
        ),
    ]
